### ISSUE TITLE
⚔ Changes for v1.2.0

### ISSUE THREAD

**Issue by pawelWritesCode** [pawelWritesCode/gdutils#36]
### Changes

1. Few changes in service `DebuggerService` from `debugger` subpackage.
2. Support for HTML
- ability to detect HTML format
- ability to query HTML nodes to assert against in appropriate methods
3. Research
- see whether [antchfx/jsonquery](https://github.com/antchfx/jsonquery) may be used as `PathFinder` implementation in `pathfinder` subpackage
- see whether [qri-io/jsonschema](https://github.com/qri-io/jsonschema) may be used as json schema validator implementation into `schema` subpackage.

### TODO:
- [ ] Make changes in `DebuggerService` from `debugger` subpackage
- [ ] Add support for HTML
- [ ] Do research for new `PathFinder` and `Validator`

PS: all changes should be merged to `v1.2.0` branch created for this issue
